name: Android Build libfuse-dev

on:
  workflow_dispatch:
    inputs:
      target_arch:
        description: 'Target architecture (aarch64/arm/x86_64/i686)'
        required: false
        default: 'aarch64'
      ndk_version:
        description: 'Android NDK version'
        required: false
        default: 'r27c'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: ${{ github.event.inputs.ndk_version || 'r27c' }}

    - name: Install dependencies
      run: |
        sudo apt-get install -y -qq build-essential pipx python3-venv pkg-config \
        cmake docbook2x python3-pip pipx
        
        pipx ensurepath
        pipx install meson==0.61
        pipx install ninja

    - name: Build libfuse
      run: |
        sed -i "s|android-ndk-r27c|$ANDROID_NDK_HOME|g" aarch64-android-api30.txt
        
        meson setup build -Dprefix=/data/sysroot --cross-file aarch64-android-api30.txt
        meson compile -C build
        sudo ninja -C build install
        echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Upload artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        name: android-${{ github.event.inputs.target_arch || 'aarch64' }}-libfuse
        path: /data/sysroot/*

    - name: Create a ZIP file for artifact
      run: zip -r android-${{ github.event.inputs.target_arch || 'aarch64' }}-libfuse-dev.zip /data/sysroot/*
    
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.RELEASE_DATE }}
        name: Release ${{ env.RELEASE_DATE }}
        body: TODO New Release.
        draft: false
        prerelease: false
        files: |
            android-${{ github.event.inputs.target_arch || 'aarch64' }}-libfuse-dev.zip
